=== compmec/section/src/compmec/section/schema/section.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "definitions": {
    "material": {
      "type": "object",
      "properties": {
        "young_modulus": {"type": "number"},
        "poissons_ratio": {"type": "number"},
        "lame1": {"type": "number"},
        "lame2": {"type": "number"},
        "bulk_modulus": {"type": "number"},
        "shear_modulus": {"type": "number"},
        "pwave_modulus": {"type": "number"}
      },
      "anyOf": [
        {"required": ["young_modulus", "poissons_ratio"]},
        {"required": ["young_modulus", "lame1"]},
        {"required": ["young_modulus", "lame2"]},
        {"required": ["young_modulus", "shear_modulus"]},
        {"required": ["young_modulus", "bulk_modulus"]},
        {"required": ["young_modulus", "pwave_modulus"]},
        {"required": ["lame1", "lame2"]},
        {"required": ["lame1", "shear_modulus"]},
        {"required": ["lame1", "poissons_ratio"]},
        {"required": ["lame1", "bulk_modulus"]},
        {"required": ["lame1", "pwave_modulus"]},
        {"required": ["bulk_modulus", "lame2"]},
        {"required": ["bulk_modulus", "shear_modulus"]},
        {"required": ["bulk_modulus", "poissons_ratio"]},
        {"required": ["bulk_modulus", "pwave_modulus"]},
        {"required": ["lame2", "poissons_ratio"]},
        {"required": ["lame2", "pwave_modulus"]},
        {"required": ["shear_modulus", "poissons_ratio"]},
        {"required": ["shear_modulus", "pwave_modulus"]},
        {"required": ["poissons_ratio", "pwave_modulus"]}
      ]
    },
    "degree": {
      "type": "integer",
      "minimum": 1
    },
    "node_label": {
      "type": "integer",
      "minimum": 1
    },
    "curve_label": {
      "type": "integer",
      "minimum": 1
    },
    "node": {
      "type": "array",
      "items": [
          {"$ref": "#/definitions/node_label"},
          {"type": "number"},
          {"type": "number"}
      ]
    },
    "knotvector": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "curve": {
      "type": "object",
      "required": [
        "label",
        "knotvector",
        "ctrlpoints"
      ],
      "properties": {
        "label": {"$ref": "#/definitions/curve_label"},
        "degree": {"$ref": "#/definitions/degree"},
        "knotvector": {"$ref": "#/definitions/knotvector"},
        "ctrlpoints": {
            "type": "array",
            "items": {"$ref": "#/definitions/node_label"}
        },
        "weights": {
            "type": "array",
            "items": {"type": "number"}
        }
      }
    },
    "shape": {
      "type": "array",
      "items": {"$ref": "#/definitions/curve_label"}
    },
    "section": {
      "type": "object",
      "additionalProperties": {
        "shapes": {"type": "array", "items": {"type": "string"}},
        "materials": {"type": "array", "items": {"type": "string"}}
      }
    }
  },
  "type": "object",
  "title": "Root Schema",
  "required": [
    "nodes",
    "curves",
    "shapes",
    "materials",
    "sections"
  ],
  "properties": {
    "nodes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/node"
      }
    },
    "curves": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/curve"
      }
    },
    "shapes": {
      "type": "object",
      "additionalProperties": {"$ref": "#/definitions/shape"}
    },
    "materials": {
      "type": "object",
      "additionalProperties": {"$ref": "#/definitions/material"}
    },
    "sections": {
      "type": "object",
      "additionalProperties": {"$ref": "#/definitions/section"}
    }
  }
}

=== compmec/section/examples/steel_square.json
{
    "nodes": [
        [1, 1, 1],
        [2, -1, 1],
        [3, -1, -1],
        [4, -1, -1]
    ],
    "curves": [
        {"label": 1000,
        "degree": 1,
        "knotvector": [0, 0, 0.25, 0.5, 0.75, 1, 1],
        "ctrlpoints": [1, 2, 3, 4, 1]}
    ],
    "shapes": {
        "square": [1000]
    },
    "materials": {
        "steel": {
            "young_modulus": 210e+3,
            "poissons_ratio": 0.3
        }
    },
    "sections": {
        "square": {
            "shapes": ["square"],
            "materials": ["steel"]
        }
    }
}
